<!DOCTYPE html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style>
    body {
      font-family: 'DejaVu Sans', serif;
      color: #334155;
      line-height: 1.6;
    }

    .header {
      text-align: center;
      border-bottom: 2px solid #f1f5f9;
      padding-bottom: 20px;
    }

    .question {
      font-style: italic;
      font-size: 1.2rem;
      color: #b45309;
      margin: 20px 0;
    }

    .hexagram-box {
      margin: 30px 0;
      padding: 20px;
      border: 1px solid #e2e8f0;
      border-radius: 10px;
    }

    .line-item {
      margin-bottom: 15px;
      padding-left: 10px;
      border-left: 3px solid #e2e8f0;
    }

    .changing {
      border-left-color: #f59e0b;
      background-color: #fffbeb;
    }

    .footer {
      margin-top: 50px;
      font-size: 0.8rem;
      text-align: center;
      color: #94a3b8;
    }

    /* .page-break {
      page-break-after: always;
    } */
  </style>
</head>

<body>
  <div class="header">
    <h1>I-Ching Oracle Report</h1>
    <p>{{ $reading->created_at->format('F d, Y — H:i') }}</p>
  </div>

  <div class="question">
    "{{ $reading->question }}"
  </div>

  <div class="hexagram-box">
    <h2>Primary Hexagram: {{ $reading->hexagram->number }}. {{ $reading->hexagram->character }}</h2>
    <p><strong>{{ $reading->hexagram->names[0] }}</strong></p>
    <p>{{ $reading->hexagram->judgment }}</p>
  </div>

  <h3>Line Guidance</h3>
  @foreach ($reading->hexagram->hexagramLines as $line)
    @php $isChanging = in_array($line->position, $changing_lines); @endphp
    <div class="line-item {{ $isChanging ? 'changing' : '' }}">
      <strong>Line {{ $line->position }}:</strong> {{ $isChanging ? '[CHANGING]' : '' }}<br>
      {{ $line->meaning }}
    </div>
  @endforeach

  @if ($secondary_hexagram)
    {{-- <div class="page-break"></div> --}}
    <div class="hexagram-box">
      <h2>Relating Hexagram: {{ $secondary_hexagram->number }}. {{ $secondary_hexagram->character }}</h2>
      <p><strong>{{ $secondary_hexagram->names[0] }}</strong></p>
      <p>{{ $secondary_hexagram->judgment }}</p>
    </div>
  @endif

  <div class="footer">
    Generated by I-Ching Cabinet. Trust the process.
  </div>
</body>

</html>
